logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost:5432}/${PG_DB:notification_gateway}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate